// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.21.12
// source: watchtower.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	WatchtowerService_Ingest_FullMethodName       = "/watchtower.v1.WatchtowerService/Ingest"
	WatchtowerService_IngestStream_FullMethodName = "/watchtower.v1.WatchtowerService/IngestStream"
)

// WatchtowerServiceClient is the client API for WatchtowerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// WatchtowerService is the gRPC API exposed by every Watchtower instance.
type WatchtowerServiceClient interface {
	// Ingest receives a batch of log records (unary RPC — simple, retryable).
	Ingest(ctx context.Context, in *LogBatch, opts ...grpc.CallOption) (*IngestResponse, error)
	// IngestStream allows high-throughput streaming from long-lived connections.
	// The client streams batches; the server acks periodically.
	IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LogBatch, IngestResponse], error)
}

type watchtowerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewWatchtowerServiceClient(cc grpc.ClientConnInterface) WatchtowerServiceClient {
	return &watchtowerServiceClient{cc}
}

func (c *watchtowerServiceClient) Ingest(ctx context.Context, in *LogBatch, opts ...grpc.CallOption) (*IngestResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IngestResponse)
	err := c.cc.Invoke(ctx, WatchtowerService_Ingest_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *watchtowerServiceClient) IngestStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[LogBatch, IngestResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &WatchtowerService_ServiceDesc.Streams[0], WatchtowerService_IngestStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[LogBatch, IngestResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WatchtowerService_IngestStreamClient = grpc.BidiStreamingClient[LogBatch, IngestResponse]

// WatchtowerServiceServer is the server API for WatchtowerService service.
// All implementations must embed UnimplementedWatchtowerServiceServer
// for forward compatibility.
//
// WatchtowerService is the gRPC API exposed by every Watchtower instance.
type WatchtowerServiceServer interface {
	// Ingest receives a batch of log records (unary RPC — simple, retryable).
	Ingest(context.Context, *LogBatch) (*IngestResponse, error)
	// IngestStream allows high-throughput streaming from long-lived connections.
	// The client streams batches; the server acks periodically.
	IngestStream(grpc.BidiStreamingServer[LogBatch, IngestResponse]) error
	mustEmbedUnimplementedWatchtowerServiceServer()
}

// UnimplementedWatchtowerServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedWatchtowerServiceServer struct{}

func (UnimplementedWatchtowerServiceServer) Ingest(context.Context, *LogBatch) (*IngestResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Ingest not implemented")
}
func (UnimplementedWatchtowerServiceServer) IngestStream(grpc.BidiStreamingServer[LogBatch, IngestResponse]) error {
	return status.Error(codes.Unimplemented, "method IngestStream not implemented")
}
func (UnimplementedWatchtowerServiceServer) mustEmbedUnimplementedWatchtowerServiceServer() {}
func (UnimplementedWatchtowerServiceServer) testEmbeddedByValue()                           {}

// UnsafeWatchtowerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WatchtowerServiceServer will
// result in compilation errors.
type UnsafeWatchtowerServiceServer interface {
	mustEmbedUnimplementedWatchtowerServiceServer()
}

func RegisterWatchtowerServiceServer(s grpc.ServiceRegistrar, srv WatchtowerServiceServer) {
	// If the following call panics, it indicates UnimplementedWatchtowerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&WatchtowerService_ServiceDesc, srv)
}

func _WatchtowerService_Ingest_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LogBatch)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WatchtowerServiceServer).Ingest(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: WatchtowerService_Ingest_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WatchtowerServiceServer).Ingest(ctx, req.(*LogBatch))
	}
	return interceptor(ctx, in, info, handler)
}

func _WatchtowerService_IngestStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(WatchtowerServiceServer).IngestStream(&grpc.GenericServerStream[LogBatch, IngestResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type WatchtowerService_IngestStreamServer = grpc.BidiStreamingServer[LogBatch, IngestResponse]

// WatchtowerService_ServiceDesc is the grpc.ServiceDesc for WatchtowerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WatchtowerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "watchtower.v1.WatchtowerService",
	HandlerType: (*WatchtowerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ingest",
			Handler:    _WatchtowerService_Ingest_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "IngestStream",
			Handler:       _WatchtowerService_IngestStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "watchtower.proto",
}
