// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: watchtower.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Severity levels aligned with OpenTelemetry and syslog conventions.
type Severity int32

const (
	Severity_SEVERITY_UNSPECIFIED Severity = 0
	Severity_SEVERITY_TRACE       Severity = 1
	Severity_SEVERITY_DEBUG       Severity = 5
	Severity_SEVERITY_INFO        Severity = 9
	Severity_SEVERITY_WARN        Severity = 13
	Severity_SEVERITY_ERROR       Severity = 17
	Severity_SEVERITY_FATAL       Severity = 21
)

// Enum value maps for Severity.
var (
	Severity_name = map[int32]string{
		0:  "SEVERITY_UNSPECIFIED",
		1:  "SEVERITY_TRACE",
		5:  "SEVERITY_DEBUG",
		9:  "SEVERITY_INFO",
		13: "SEVERITY_WARN",
		17: "SEVERITY_ERROR",
		21: "SEVERITY_FATAL",
	}
	Severity_value = map[string]int32{
		"SEVERITY_UNSPECIFIED": 0,
		"SEVERITY_TRACE":       1,
		"SEVERITY_DEBUG":       5,
		"SEVERITY_INFO":        9,
		"SEVERITY_WARN":        13,
		"SEVERITY_ERROR":       17,
		"SEVERITY_FATAL":       21,
	}
)

func (x Severity) Enum() *Severity {
	p := new(Severity)
	*p = x
	return p
}

func (x Severity) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Severity) Descriptor() protoreflect.EnumDescriptor {
	return file_watchtower_proto_enumTypes[0].Descriptor()
}

func (Severity) Type() protoreflect.EnumType {
	return &file_watchtower_proto_enumTypes[0]
}

func (x Severity) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Severity.Descriptor instead.
func (Severity) EnumDescriptor() ([]byte, []int) {
	return file_watchtower_proto_rawDescGZIP(), []int{0}
}

// KeyValue is a lightweight typed attribute to avoid reflection overhead.
type KeyValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         *AnyValue              `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KeyValue) Reset() {
	*x = KeyValue{}
	mi := &file_watchtower_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KeyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KeyValue) ProtoMessage() {}

func (x *KeyValue) ProtoReflect() protoreflect.Message {
	mi := &file_watchtower_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KeyValue.ProtoReflect.Descriptor instead.
func (*KeyValue) Descriptor() ([]byte, []int) {
	return file_watchtower_proto_rawDescGZIP(), []int{0}
}

func (x *KeyValue) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KeyValue) GetValue() *AnyValue {
	if x != nil {
		return x.Value
	}
	return nil
}

// AnyValue supports common log field types without paying for google.protobuf.Any
// envelope overhead. This keeps serialization compact and CPU-friendly.
type AnyValue struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Value:
	//
	//	*AnyValue_StringValue
	//	*AnyValue_IntValue
	//	*AnyValue_DoubleValue
	//	*AnyValue_BoolValue
	//	*AnyValue_BytesValue
	//	*AnyValue_ArrayValue
	//	*AnyValue_MapValue
	Value         isAnyValue_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnyValue) Reset() {
	*x = AnyValue{}
	mi := &file_watchtower_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnyValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnyValue) ProtoMessage() {}

func (x *AnyValue) ProtoReflect() protoreflect.Message {
	mi := &file_watchtower_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnyValue.ProtoReflect.Descriptor instead.
func (*AnyValue) Descriptor() ([]byte, []int) {
	return file_watchtower_proto_rawDescGZIP(), []int{1}
}

func (x *AnyValue) GetValue() isAnyValue_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *AnyValue) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *AnyValue) GetIntValue() int64 {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_IntValue); ok {
			return x.IntValue
		}
	}
	return 0
}

func (x *AnyValue) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *AnyValue) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *AnyValue) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *AnyValue) GetArrayValue() *ArrayValue {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_ArrayValue); ok {
			return x.ArrayValue
		}
	}
	return nil
}

func (x *AnyValue) GetMapValue() *MapValue {
	if x != nil {
		if x, ok := x.Value.(*AnyValue_MapValue); ok {
			return x.MapValue
		}
	}
	return nil
}

type isAnyValue_Value interface {
	isAnyValue_Value()
}

type AnyValue_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type AnyValue_IntValue struct {
	IntValue int64 `protobuf:"varint,2,opt,name=int_value,json=intValue,proto3,oneof"`
}

type AnyValue_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,3,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type AnyValue_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type AnyValue_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,5,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type AnyValue_ArrayValue struct {
	ArrayValue *ArrayValue `protobuf:"bytes,6,opt,name=array_value,json=arrayValue,proto3,oneof"`
}

type AnyValue_MapValue struct {
	MapValue *MapValue `protobuf:"bytes,7,opt,name=map_value,json=mapValue,proto3,oneof"`
}

func (*AnyValue_StringValue) isAnyValue_Value() {}

func (*AnyValue_IntValue) isAnyValue_Value() {}

func (*AnyValue_DoubleValue) isAnyValue_Value() {}

func (*AnyValue_BoolValue) isAnyValue_Value() {}

func (*AnyValue_BytesValue) isAnyValue_Value() {}

func (*AnyValue_ArrayValue) isAnyValue_Value() {}

func (*AnyValue_MapValue) isAnyValue_Value() {}

type ArrayValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*AnyValue            `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArrayValue) Reset() {
	*x = ArrayValue{}
	mi := &file_watchtower_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArrayValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayValue) ProtoMessage() {}

func (x *ArrayValue) ProtoReflect() protoreflect.Message {
	mi := &file_watchtower_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayValue.ProtoReflect.Descriptor instead.
func (*ArrayValue) Descriptor() ([]byte, []int) {
	return file_watchtower_proto_rawDescGZIP(), []int{2}
}

func (x *ArrayValue) GetValues() []*AnyValue {
	if x != nil {
		return x.Values
	}
	return nil
}

type MapValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*KeyValue            `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapValue) Reset() {
	*x = MapValue{}
	mi := &file_watchtower_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapValue) ProtoMessage() {}

func (x *MapValue) ProtoReflect() protoreflect.Message {
	mi := &file_watchtower_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapValue.ProtoReflect.Descriptor instead.
func (*MapValue) Descriptor() ([]byte, []int) {
	return file_watchtower_proto_rawDescGZIP(), []int{3}
}

func (x *MapValue) GetEntries() []*KeyValue {
	if x != nil {
		return x.Entries
	}
	return nil
}

// LogRecord is the core unit of data flowing through Watchtower.
// Designed for flexible schemas: mandatory fields are cheap fixed-size types,
// everything else is carried in the attributes map.
type LogRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Nanosecond-precision timestamp of when the log was generated.
	Timestamp *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// Severity of the log entry.
	Severity Severity `protobuf:"varint,2,opt,name=severity,proto3,enum=watchtower.v1.Severity" json:"severity,omitempty"`
	// Human-readable log message body.
	Body string `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	// Structured attributes — the flexible schema extension point.
	// Applications attach any domain-specific fields here.
	Attributes []*KeyValue `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty"`
	// Resource identity: which service/host/instance produced this log.
	Resource *Resource `protobuf:"bytes,5,opt,name=resource,proto3" json:"resource,omitempty"`
	// Optional trace correlation for distributed tracing integration.
	TraceId []byte `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	SpanId  []byte `protobuf:"bytes,7,opt,name=span_id,json=spanId,proto3" json:"span_id,omitempty"`
	// Schema URL that describes the attribute layout for this record.
	// Allows downstream consumers to interpret the flexible schema.
	SchemaUrl     string `protobuf:"bytes,8,opt,name=schema_url,json=schemaUrl,proto3" json:"schema_url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_watchtower_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_watchtower_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_watchtower_proto_rawDescGZIP(), []int{4}
}

func (x *LogRecord) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *LogRecord) GetSeverity() Severity {
	if x != nil {
		return x.Severity
	}
	return Severity_SEVERITY_UNSPECIFIED
}

func (x *LogRecord) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

func (x *LogRecord) GetAttributes() []*KeyValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *LogRecord) GetResource() *Resource {
	if x != nil {
		return x.Resource
	}
	return nil
}

func (x *LogRecord) GetTraceId() []byte {
	if x != nil {
		return x.TraceId
	}
	return nil
}

func (x *LogRecord) GetSpanId() []byte {
	if x != nil {
		return x.SpanId
	}
	return nil
}

func (x *LogRecord) GetSchemaUrl() string {
	if x != nil {
		return x.SchemaUrl
	}
	return ""
}

// Resource describes the entity producing logs.
type Resource struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	HostName      string                 `protobuf:"bytes,2,opt,name=host_name,json=hostName,proto3" json:"host_name,omitempty"`
	InstanceId    string                 `protobuf:"bytes,3,opt,name=instance_id,json=instanceId,proto3" json:"instance_id,omitempty"`
	Attributes    []*KeyValue            `protobuf:"bytes,4,rep,name=attributes,proto3" json:"attributes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resource) Reset() {
	*x = Resource{}
	mi := &file_watchtower_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resource) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resource) ProtoMessage() {}

func (x *Resource) ProtoReflect() protoreflect.Message {
	mi := &file_watchtower_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resource.ProtoReflect.Descriptor instead.
func (*Resource) Descriptor() ([]byte, []int) {
	return file_watchtower_proto_rawDescGZIP(), []int{5}
}

func (x *Resource) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *Resource) GetHostName() string {
	if x != nil {
		return x.HostName
	}
	return ""
}

func (x *Resource) GetInstanceId() string {
	if x != nil {
		return x.InstanceId
	}
	return ""
}

func (x *Resource) GetAttributes() []*KeyValue {
	if x != nil {
		return x.Attributes
	}
	return nil
}

// LogBatch groups multiple records for network-efficient transmission.
// The collector and forwarder always operate on batches.
type LogBatch struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Records []*LogRecord           `protobuf:"bytes,1,rep,name=records,proto3" json:"records,omitempty"`
	// Optional batch-level metadata (e.g., compression hint, schema version).
	Metadata      map[string]string `protobuf:"bytes,2,rep,name=metadata,proto3" json:"metadata,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogBatch) Reset() {
	*x = LogBatch{}
	mi := &file_watchtower_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogBatch) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogBatch) ProtoMessage() {}

func (x *LogBatch) ProtoReflect() protoreflect.Message {
	mi := &file_watchtower_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogBatch.ProtoReflect.Descriptor instead.
func (*LogBatch) Descriptor() ([]byte, []int) {
	return file_watchtower_proto_rawDescGZIP(), []int{6}
}

func (x *LogBatch) GetRecords() []*LogRecord {
	if x != nil {
		return x.Records
	}
	return nil
}

func (x *LogBatch) GetMetadata() map[string]string {
	if x != nil {
		return x.Metadata
	}
	return nil
}

// IngestResponse acknowledges a batch.
type IngestResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Number of records accepted.
	AcceptedCount int64 `protobuf:"varint,1,opt,name=accepted_count,json=acceptedCount,proto3" json:"accepted_count,omitempty"`
	// If non-empty, partial failure details keyed by record index.
	Errors        map[int64]string `protobuf:"bytes,2,rep,name=errors,proto3" json:"errors,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IngestResponse) Reset() {
	*x = IngestResponse{}
	mi := &file_watchtower_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IngestResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IngestResponse) ProtoMessage() {}

func (x *IngestResponse) ProtoReflect() protoreflect.Message {
	mi := &file_watchtower_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IngestResponse.ProtoReflect.Descriptor instead.
func (*IngestResponse) Descriptor() ([]byte, []int) {
	return file_watchtower_proto_rawDescGZIP(), []int{7}
}

func (x *IngestResponse) GetAcceptedCount() int64 {
	if x != nil {
		return x.AcceptedCount
	}
	return 0
}

func (x *IngestResponse) GetErrors() map[int64]string {
	if x != nil {
		return x.Errors
	}
	return nil
}

var File_watchtower_proto protoreflect.FileDescriptor

const file_watchtower_proto_rawDesc = "" +
	"\n" +
	"\x10watchtower.proto\x12\rwatchtower.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"K\n" +
	"\bKeyValue\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12-\n" +
	"\x05value\x18\x02 \x01(\v2\x17.watchtower.v1.AnyValueR\x05value\"\xb6\x02\n" +
	"\bAnyValue\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1d\n" +
	"\tint_value\x18\x02 \x01(\x03H\x00R\bintValue\x12#\n" +
	"\fdouble_value\x18\x03 \x01(\x01H\x00R\vdoubleValue\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12!\n" +
	"\vbytes_value\x18\x05 \x01(\fH\x00R\n" +
	"bytesValue\x12<\n" +
	"\varray_value\x18\x06 \x01(\v2\x19.watchtower.v1.ArrayValueH\x00R\n" +
	"arrayValue\x126\n" +
	"\tmap_value\x18\a \x01(\v2\x17.watchtower.v1.MapValueH\x00R\bmapValueB\a\n" +
	"\x05value\"=\n" +
	"\n" +
	"ArrayValue\x12/\n" +
	"\x06values\x18\x01 \x03(\v2\x17.watchtower.v1.AnyValueR\x06values\"=\n" +
	"\bMapValue\x121\n" +
	"\aentries\x18\x01 \x03(\v2\x17.watchtower.v1.KeyValueR\aentries\"\xcf\x02\n" +
	"\tLogRecord\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x123\n" +
	"\bseverity\x18\x02 \x01(\x0e2\x17.watchtower.v1.SeverityR\bseverity\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body\x127\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2\x17.watchtower.v1.KeyValueR\n" +
	"attributes\x123\n" +
	"\bresource\x18\x05 \x01(\v2\x17.watchtower.v1.ResourceR\bresource\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\fR\atraceId\x12\x17\n" +
	"\aspan_id\x18\a \x01(\fR\x06spanId\x12\x1d\n" +
	"\n" +
	"schema_url\x18\b \x01(\tR\tschemaUrl\"\xa4\x01\n" +
	"\bResource\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12\x1b\n" +
	"\thost_name\x18\x02 \x01(\tR\bhostName\x12\x1f\n" +
	"\vinstance_id\x18\x03 \x01(\tR\n" +
	"instanceId\x127\n" +
	"\n" +
	"attributes\x18\x04 \x03(\v2\x17.watchtower.v1.KeyValueR\n" +
	"attributes\"\xbe\x01\n" +
	"\bLogBatch\x122\n" +
	"\arecords\x18\x01 \x03(\v2\x18.watchtower.v1.LogRecordR\arecords\x12A\n" +
	"\bmetadata\x18\x02 \x03(\v2%.watchtower.v1.LogBatch.MetadataEntryR\bmetadata\x1a;\n" +
	"\rMetadataEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb5\x01\n" +
	"\x0eIngestResponse\x12%\n" +
	"\x0eaccepted_count\x18\x01 \x01(\x03R\racceptedCount\x12A\n" +
	"\x06errors\x18\x02 \x03(\v2).watchtower.v1.IngestResponse.ErrorsEntryR\x06errors\x1a9\n" +
	"\vErrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\x03R\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01*\x9a\x01\n" +
	"\bSeverity\x12\x18\n" +
	"\x14SEVERITY_UNSPECIFIED\x10\x00\x12\x12\n" +
	"\x0eSEVERITY_TRACE\x10\x01\x12\x12\n" +
	"\x0eSEVERITY_DEBUG\x10\x05\x12\x11\n" +
	"\rSEVERITY_INFO\x10\t\x12\x11\n" +
	"\rSEVERITY_WARN\x10\r\x12\x12\n" +
	"\x0eSEVERITY_ERROR\x10\x11\x12\x12\n" +
	"\x0eSEVERITY_FATAL\x10\x152\xa1\x01\n" +
	"\x11WatchtowerService\x12@\n" +
	"\x06Ingest\x12\x17.watchtower.v1.LogBatch\x1a\x1d.watchtower.v1.IngestResponse\x12J\n" +
	"\fIngestStream\x12\x17.watchtower.v1.LogBatch\x1a\x1d.watchtower.v1.IngestResponse(\x010\x01B+Z)github.com/TellurianCorp/watchtower/protob\x06proto3"

var (
	file_watchtower_proto_rawDescOnce sync.Once
	file_watchtower_proto_rawDescData []byte
)

func file_watchtower_proto_rawDescGZIP() []byte {
	file_watchtower_proto_rawDescOnce.Do(func() {
		file_watchtower_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_watchtower_proto_rawDesc), len(file_watchtower_proto_rawDesc)))
	})
	return file_watchtower_proto_rawDescData
}

var file_watchtower_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_watchtower_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_watchtower_proto_goTypes = []any{
	(Severity)(0),                 // 0: watchtower.v1.Severity
	(*KeyValue)(nil),              // 1: watchtower.v1.KeyValue
	(*AnyValue)(nil),              // 2: watchtower.v1.AnyValue
	(*ArrayValue)(nil),            // 3: watchtower.v1.ArrayValue
	(*MapValue)(nil),              // 4: watchtower.v1.MapValue
	(*LogRecord)(nil),             // 5: watchtower.v1.LogRecord
	(*Resource)(nil),              // 6: watchtower.v1.Resource
	(*LogBatch)(nil),              // 7: watchtower.v1.LogBatch
	(*IngestResponse)(nil),        // 8: watchtower.v1.IngestResponse
	nil,                           // 9: watchtower.v1.LogBatch.MetadataEntry
	nil,                           // 10: watchtower.v1.IngestResponse.ErrorsEntry
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
}
var file_watchtower_proto_depIdxs = []int32{
	2,  // 0: watchtower.v1.KeyValue.value:type_name -> watchtower.v1.AnyValue
	3,  // 1: watchtower.v1.AnyValue.array_value:type_name -> watchtower.v1.ArrayValue
	4,  // 2: watchtower.v1.AnyValue.map_value:type_name -> watchtower.v1.MapValue
	2,  // 3: watchtower.v1.ArrayValue.values:type_name -> watchtower.v1.AnyValue
	1,  // 4: watchtower.v1.MapValue.entries:type_name -> watchtower.v1.KeyValue
	11, // 5: watchtower.v1.LogRecord.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 6: watchtower.v1.LogRecord.severity:type_name -> watchtower.v1.Severity
	1,  // 7: watchtower.v1.LogRecord.attributes:type_name -> watchtower.v1.KeyValue
	6,  // 8: watchtower.v1.LogRecord.resource:type_name -> watchtower.v1.Resource
	1,  // 9: watchtower.v1.Resource.attributes:type_name -> watchtower.v1.KeyValue
	5,  // 10: watchtower.v1.LogBatch.records:type_name -> watchtower.v1.LogRecord
	9,  // 11: watchtower.v1.LogBatch.metadata:type_name -> watchtower.v1.LogBatch.MetadataEntry
	10, // 12: watchtower.v1.IngestResponse.errors:type_name -> watchtower.v1.IngestResponse.ErrorsEntry
	7,  // 13: watchtower.v1.WatchtowerService.Ingest:input_type -> watchtower.v1.LogBatch
	7,  // 14: watchtower.v1.WatchtowerService.IngestStream:input_type -> watchtower.v1.LogBatch
	8,  // 15: watchtower.v1.WatchtowerService.Ingest:output_type -> watchtower.v1.IngestResponse
	8,  // 16: watchtower.v1.WatchtowerService.IngestStream:output_type -> watchtower.v1.IngestResponse
	15, // [15:17] is the sub-list for method output_type
	13, // [13:15] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_watchtower_proto_init() }
func file_watchtower_proto_init() {
	if File_watchtower_proto != nil {
		return
	}
	file_watchtower_proto_msgTypes[1].OneofWrappers = []any{
		(*AnyValue_StringValue)(nil),
		(*AnyValue_IntValue)(nil),
		(*AnyValue_DoubleValue)(nil),
		(*AnyValue_BoolValue)(nil),
		(*AnyValue_BytesValue)(nil),
		(*AnyValue_ArrayValue)(nil),
		(*AnyValue_MapValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_watchtower_proto_rawDesc), len(file_watchtower_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_watchtower_proto_goTypes,
		DependencyIndexes: file_watchtower_proto_depIdxs,
		EnumInfos:         file_watchtower_proto_enumTypes,
		MessageInfos:      file_watchtower_proto_msgTypes,
	}.Build()
	File_watchtower_proto = out.File
	file_watchtower_proto_goTypes = nil
	file_watchtower_proto_depIdxs = nil
}
